# --------------------------------
# Site settings
title: Hub3c VideoChat 
author: Ben Anggoro
email: ben@benworkandplay.com
project: Geekseat
description: > # this means to ignore newlines until "baseurl:"
  App prototype in HTML/CSS/JS

# --------------------------------
# Environment Settings
environment: dev
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://aesinv.com" # the base hostname & protocol for your site
url: "http://dev.aesinv.com:4000"
source: project
destination: _dist

# --------------------------------
# Seasonal Support
seasonal_assets_url: seasonal/

# Games Done Quick Event
gdq_event: false
gdq_name: Awesome Games Done Quick 2016
gdq_description: >
  AGDQ a giant gaming party extravaganza and it raises money for the Prevent Cancer Foundation.<br /><br />Please tune in, enjoy the stream, and donate.
gdq_banner: AGDQ2016.jpg

# --------------------------------
# Social Networking
twitter_username: benworkandplay
github_username:  benbkk
instagram_username: ben_bkk

# --------------------------------
# Build settings
markdown: kramdown
safe: false
future: true
paginate: 5

# Category Handling
category_dir: /
tag_dir: /tag/

# --------------------------------
# Includes & Excludes
exclude: [css/]
include: [js/,fonts/,icons/]

# --------------------------------
# Suggested Tweets
suggested_tweet:
  url:        'http://www.benworkandplay.com'
  via:        'benworkandplay'
  hashtags:   []
  related:    []
